baseURL = "https://eragoste.github.io/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Timmy LIAUD"
theme = "dream"

disqusShortname = "Timmy LIAUD"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#fff"
  linkColor = "seagreen"

  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"

  images = ["me/"]

  author = "Timmy LIAUD"
  description = "portfolio of Timmy LIAUD"
  avatar = "/me/yy.jpeg"
  headerTitle = "Timmy LIAUD"
  motto = "<p style=\"margin:0\">Welcome to my portfolio, my name is Timmy LIAUD i'm 22 years old </p><p style=\"margin:0\">Voici quelques uns de mes projets</p> <p>Feel free to check my personal information by clicking <i class=\"link icon dream-flip-toggle\" title=\"Retourne ça!\"><a>here</a></i></p>"

  rss = true

  linkedin = "timmy-liaud"
  github = "eragoste"

  siteStartYear = 2021

  favicon = "/favicon.ico"

  highlightjs = true
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  enableSearch = true

  showSummaryCoverInPost = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []
